export const mockPropsForCancerSummaryContainer = {
    samplesExtendedWithClinicalData: [
        {
            uniqueSampleKey: 'QjA4NTpjaG9sX251c18yMDEy',
            uniquePatientKey: 'QjA4NTpjaG9sX251c18yMDEy',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'B085',
            patientId: 'B085',
            cancerTypeId: 'chol',
            studyId: 'chol_nus_2012',
            cancerType: 'Hepatobiliary Cancer',
            cancerTypeDetailed: 'Cholangiocarcinoma',
        },
        {
            uniqueSampleKey: 'QjA5OTpjaG9sX251c18yMDEy',
            uniquePatientKey: 'QjA5OTpjaG9sX251c18yMDEy',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'B099',
            patientId: 'B099',
            cancerTypeId: 'chol',
            studyId: 'chol_nus_2012',
            cancerType: 'Hepatobiliary Cancer',
            cancerTypeDetailed: 'Cholangiocarcinoma',
        },
        {
            uniqueSampleKey: 'UjEwNDpjaG9sX251c18yMDEy',
            uniquePatientKey: 'UjEwNDpjaG9sX251c18yMDEy',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'R104',
            patientId: 'R104',
            cancerTypeId: 'chol',
            studyId: 'chol_nus_2012',
            cancerType: 'Hepatobiliary Cancer',
            cancerTypeDetailed: 'Cholangiocarcinoma',
        },
        {
            uniqueSampleKey: 'VDAyNjpjaG9sX251c18yMDEy',
            uniquePatientKey: 'VDAyNjpjaG9sX251c18yMDEy',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'T026',
            patientId: 'T026',
            cancerTypeId: 'chol',
            studyId: 'chol_nus_2012',
            cancerType: 'Hepatobiliary Cancer',
            cancerTypeDetailed: 'Cholangiocarcinoma',
        },
        {
            uniqueSampleKey: 'VTA0NDpjaG9sX251c18yMDEy',
            uniquePatientKey: 'VTA0NDpjaG9sX251c18yMDEy',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'U044',
            patientId: 'U044',
            cancerTypeId: 'chol',
            studyId: 'chol_nus_2012',
            cancerType: 'Hepatobiliary Cancer',
            cancerTypeDetailed: 'Cholangiocarcinoma',
        },
        {
            uniqueSampleKey: 'VzAxMjpjaG9sX251c18yMDEy',
            uniquePatientKey: 'VzAxMjpjaG9sX251c18yMDEy',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'W012',
            patientId: 'W012',
            cancerTypeId: 'chol',
            studyId: 'chol_nus_2012',
            cancerType: 'Hepatobiliary Cancer',
            cancerTypeDetailed: 'Cholangiocarcinoma',
        },
        {
            uniqueSampleKey: 'VzAzOTpjaG9sX251c18yMDEy',
            uniquePatientKey: 'VzAzOTpjaG9sX251c18yMDEy',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'W039',
            patientId: 'W039',
            cancerTypeId: 'chol',
            studyId: 'chol_nus_2012',
            cancerType: 'Hepatobiliary Cancer',
            cancerTypeDetailed: 'Cholangiocarcinoma',
        },
        {
            uniqueSampleKey: 'VzA0MDpjaG9sX251c18yMDEy',
            uniquePatientKey: 'VzA0MDpjaG9sX251c18yMDEy',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'W040',
            patientId: 'W040',
            cancerTypeId: 'chol',
            studyId: 'chol_nus_2012',
            cancerType: 'Hepatobiliary Cancer',
            cancerTypeDetailed: 'Cholangiocarcinoma',
        },
        {
            uniqueSampleKey: 'UGFuTkVUMTBQVDpwYW5ldF9qaHVfMjAxMQ',
            uniquePatientKey: 'UEVOMTA6cGFuZXRfamh1XzIwMTE',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'PanNET10PT',
            patientId: 'PEN10',
            cancerTypeId: 'panet',
            studyId: 'panet_jhu_2011',
            cancerType: 'Pancreatic Cancer',
            cancerTypeDetailed: 'Pancreatic Neuroendocrine Tumor',
        },
        {
            uniqueSampleKey: 'UGFuTkVUMjFQVDpwYW5ldF9qaHVfMjAxMQ',
            uniquePatientKey: 'UEVOMjE6cGFuZXRfamh1XzIwMTE',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'PanNET21PT',
            patientId: 'PEN21',
            cancerTypeId: 'panet',
            studyId: 'panet_jhu_2011',
            cancerType: 'Pancreatic Cancer',
            cancerTypeDetailed: 'Pancreatic Neuroendocrine Tumor',
        },
        {
            uniqueSampleKey: 'UGFuTkVUMjNQVDpwYW5ldF9qaHVfMjAxMQ',
            uniquePatientKey: 'UEVOMjM6cGFuZXRfamh1XzIwMTE',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'PanNET23PT',
            patientId: 'PEN23',
            cancerTypeId: 'panet',
            studyId: 'panet_jhu_2011',
            cancerType: 'Pancreatic Cancer',
            cancerTypeDetailed: 'Pancreatic Neuroendocrine Tumor',
        },
        {
            uniqueSampleKey: 'UGFuTkVUMjRQVDpwYW5ldF9qaHVfMjAxMQ',
            uniquePatientKey: 'UEVOMjQ6cGFuZXRfamh1XzIwMTE',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'PanNET24PT',
            patientId: 'PEN24',
            cancerTypeId: 'panet',
            studyId: 'panet_jhu_2011',
            cancerType: 'Pancreatic Cancer',
            cancerTypeDetailed: 'Pancreatic Neuroendocrine Tumor',
        },
        {
            uniqueSampleKey: 'UGFuTkVUMjVQVDpwYW5ldF9qaHVfMjAxMQ',
            uniquePatientKey: 'UEVOMjU6cGFuZXRfamh1XzIwMTE',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'PanNET25PT',
            patientId: 'PEN25',
            cancerTypeId: 'panet',
            studyId: 'panet_jhu_2011',
            cancerType: 'Pancreatic Cancer',
            cancerTypeDetailed: 'Pancreatic Neuroendocrine Tumor',
        },
        {
            uniqueSampleKey: 'UGFuTkVUM1BUOnBhbmV0X2podV8yMDEx',
            uniquePatientKey: 'UEVOMzpwYW5ldF9qaHVfMjAxMQ',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'PanNET3PT',
            patientId: 'PEN3',
            cancerTypeId: 'panet',
            studyId: 'panet_jhu_2011',
            cancerType: 'Pancreatic Cancer',
            cancerTypeDetailed: 'Pancreatic Neuroendocrine Tumor',
        },
        {
            uniqueSampleKey: 'UGFuTkVUMzFQVDpwYW5ldF9qaHVfMjAxMQ',
            uniquePatientKey: 'UEVOMzE6cGFuZXRfamh1XzIwMTE',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'PanNET31PT',
            patientId: 'PEN31',
            cancerTypeId: 'panet',
            studyId: 'panet_jhu_2011',
            cancerType: 'Pancreatic Cancer',
            cancerTypeDetailed: 'Pancreatic Neuroendocrine Tumor',
        },
        {
            uniqueSampleKey: 'UGFuTkVUMzZQVDpwYW5ldF9qaHVfMjAxMQ',
            uniquePatientKey: 'UEVOMzY6cGFuZXRfamh1XzIwMTE',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'PanNET36PT',
            patientId: 'PEN36',
            cancerTypeId: 'panet',
            studyId: 'panet_jhu_2011',
            cancerType: 'Pancreatic Cancer',
            cancerTypeDetailed: 'Pancreatic Neuroendocrine Tumor',
        },
        {
            uniqueSampleKey: 'UGFuTkVUN1BUOnBhbmV0X2podV8yMDEx',
            uniquePatientKey: 'UEVONzpwYW5ldF9qaHVfMjAxMQ',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'PanNET7PT',
            patientId: 'PEN7',
            cancerTypeId: 'panet',
            studyId: 'panet_jhu_2011',
            cancerType: 'Pancreatic Cancer',
            cancerTypeDetailed: 'Pancreatic Neuroendocrine Tumor',
        },
        {
            uniqueSampleKey: 'UGFuTkVUOTNQVDpwYW5ldF9qaHVfMjAxMQ',
            uniquePatientKey: 'UEVOOTM6cGFuZXRfamh1XzIwMTE',
            sampleType: 'Primary Solid Tumor',
            sampleId: 'PanNET93PT',
            patientId: 'PEN93',
            cancerTypeId: 'panet',
            studyId: 'panet_jhu_2011',
            cancerType: 'Pancreatic Cancer',
            cancerTypeDetailed: 'Pancreatic Neuroendocrine Tumor',
        },
    ],
    alterationsByGeneBySampleKey: {
        KRAS: {
            UjEwNDpjaG9sX251c18yMDEy: [
                {
                    uniqueSampleKey: 'UjEwNDpjaG9sX251c18yMDEy',
                    uniquePatientKey: 'UjEwNDpjaG9sX251c18yMDEy',
                    molecularProfileId: 'chol_nus_2012_mutations',
                    sampleId: 'R104',
                    patientId: 'R104',
                    entrezGeneId: 3845,
                    gene: {
                        entrezGeneId: 3845,
                        hugoGeneSymbol: 'KRAS',
                        type: 'protein-coding',
                        cytoband: '12p12.1',
                        length: 47305,
                        chromosome: '12',
                    },
                    studyId: 'chol_nus_2012',
                    center: 'NUS',
                    mutationStatus: 'NA',
                    validationStatus: 'NA',
                    tumorAltCount: -1,
                    tumorRefCount: -1,
                    normalAltCount: -1,
                    normalRefCount: -1,
                    startPosition: 25398281,
                    endPosition: 25398281,
                    referenceAllele: 'C',
                    proteinChange: 'G13D',
                    mutationType: 'Missense_Mutation',
                    functionalImpactScore: 'M',
                    fisValue: 3.375,
                    linkXvar:
                        'getma.org/?cm=var&var=hg19,12,25398281,C,T&fts=all',
                    linkPdb:
                        'getma.org/pdb.php?prot=RASK_HUMAN&from=5&to=165&var=G13D',
                    linkMsa:
                        'getma.org/?cm=msa&ty=f&p=RASK_HUMAN&rb=5&re=165&var=G13D',
                    ncbiBuild: 'GRCh37',
                    variantType: 'SNP',
                    keyword: 'KRAS G13 missense',
                    driverFilter: '',
                    driverFilterAnnotation: '',
                    driverTiersFilter: '',
                    driverTiersFilterAnnotation: '',
                    sequenced: true,
                    wildType: false,
                    variantAllele: 'T',
                    refseqMrnaId: 'NM_033360.2',
                    proteinPosStart: 13,
                    proteinPosEnd: 13,
                    molecularProfileAlterationType: 'MUTATION_EXTENDED',
                    alterationSubType: 'missense',
                    alterationType: 'MUTATION_EXTENDED',
                },
            ],
            QjA4NTpjaG9sX251c18yMDEy: [
                {
                    uniqueSampleKey: 'QjA4NTpjaG9sX251c18yMDEy',
                    uniquePatientKey: 'QjA4NTpjaG9sX251c18yMDEy',
                    molecularProfileId: 'chol_nus_2012_mutations',
                    sampleId: 'B085',
                    patientId: 'B085',
                    entrezGeneId: 3845,
                    gene: {
                        entrezGeneId: 3845,
                        hugoGeneSymbol: 'KRAS',
                        type: 'protein-coding',
                        cytoband: '12p12.1',
                        length: 47305,
                        chromosome: '12',
                    },
                    studyId: 'chol_nus_2012',
                    center: 'NUS',
                    mutationStatus: 'NA',
                    validationStatus: 'NA',
                    tumorAltCount: -1,
                    tumorRefCount: -1,
                    normalAltCount: -1,
                    normalRefCount: -1,
                    startPosition: 25398284,
                    endPosition: 25398284,
                    referenceAllele: 'G',
                    proteinChange: 'MUTATED',
                    mutationType: 'Missense_Mutation',
                    functionalImpactScore: 'NA',
                    fisValue: 1.4013e-45,
                    linkXvar: 'NA',
                    linkPdb: 'NA',
                    linkMsa: 'NA',
                    ncbiBuild: '37',
                    variantType: 'SNP',
                    driverFilter: '',
                    driverFilterAnnotation: '',
                    driverTiersFilter: '',
                    driverTiersFilterAnnotation: '',
                    sequenced: true,
                    wildType: false,
                    variantAllele: 'C',
                    refseqMrnaId: 'NA',
                    proteinPosStart: -1,
                    proteinPosEnd: -1,
                    molecularProfileAlterationType: 'MUTATION_EXTENDED',
                    alterationSubType: 'missense',
                    alterationType: 'MUTATION_EXTENDED',
                },
            ],
            VzAxMjpjaG9sX251c18yMDEy: [
                {
                    uniqueSampleKey: 'VzAxMjpjaG9sX251c18yMDEy',
                    uniquePatientKey: 'VzAxMjpjaG9sX251c18yMDEy',
                    molecularProfileId: 'chol_nus_2012_mutations',
                    sampleId: 'W012',
                    patientId: 'W012',
                    entrezGeneId: 3845,
                    gene: {
                        entrezGeneId: 3845,
                        hugoGeneSymbol: 'KRAS',
                        type: 'protein-coding',
                        cytoband: '12p12.1',
                        length: 47305,
                        chromosome: '12',
                    },
                    studyId: 'chol_nus_2012',
                    center: 'NUS',
                    mutationStatus: 'NA',
                    validationStatus: 'NA',
                    tumorAltCount: -1,
                    tumorRefCount: -1,
                    normalAltCount: -1,
                    normalRefCount: -1,
                    startPosition: 25398284,
                    endPosition: 25398284,
                    referenceAllele: 'G',
                    proteinChange: 'MUTATED',
                    mutationType: 'Missense_Mutation',
                    functionalImpactScore: 'NA',
                    fisValue: 1.4013e-45,
                    linkXvar: 'NA',
                    linkPdb: 'NA',
                    linkMsa: 'NA',
                    ncbiBuild: '37',
                    variantType: 'SNP',
                    driverFilter: '',
                    driverFilterAnnotation: '',
                    driverTiersFilter: '',
                    driverTiersFilterAnnotation: '',
                    sequenced: true,
                    wildType: false,
                    variantAllele: 'C',
                    refseqMrnaId: 'NA',
                    proteinPosStart: -1,
                    proteinPosEnd: -1,
                    molecularProfileAlterationType: 'MUTATION_EXTENDED',
                    alterationSubType: 'missense',
                    alterationType: 'MUTATION_EXTENDED',
                },
            ],
        },
        TP53: {
            VzAxMjpjaG9sX251c18yMDEy: [
                {
                    uniqueSampleKey: 'VzAxMjpjaG9sX251c18yMDEy',
                    uniquePatientKey: 'VzAxMjpjaG9sX251c18yMDEy',
                    molecularProfileId: 'chol_nus_2012_mutations',
                    sampleId: 'W012',
                    patientId: 'W012',
                    entrezGeneId: 7157,
                    gene: {
                        entrezGeneId: 7157,
                        hugoGeneSymbol: 'TP53',
                        type: 'protein-coding',
                        cytoband: '17p13.1',
                        length: 19149,
                        chromosome: '17',
                    },
                    studyId: 'chol_nus_2012',
                    center: 'NUS',
                    mutationStatus: 'NA',
                    validationStatus: 'NA',
                    tumorAltCount: -1,
                    tumorRefCount: -1,
                    normalAltCount: -1,
                    normalRefCount: -1,
                    startPosition: 7577539,
                    endPosition: 7577539,
                    referenceAllele: 'G',
                    proteinChange: 'R248W',
                    mutationType: 'Missense_Mutation',
                    functionalImpactScore: 'M',
                    fisValue: 3.315,
                    linkXvar:
                        'getma.org/?cm=var&var=hg19,17,7577539,G,A&fts=all',
                    linkPdb:
                        'getma.org/pdb.php?prot=P53_HUMAN&from=95&to=289&var=R248W',
                    linkMsa:
                        'getma.org/?cm=msa&ty=f&p=P53_HUMAN&rb=95&re=289&var=R248W',
                    ncbiBuild: 'GRCh37',
                    variantType: 'SNP',
                    keyword: 'TP53 R248 missense',
                    driverFilter: '',
                    driverFilterAnnotation: '',
                    driverTiersFilter: '',
                    driverTiersFilterAnnotation: '',
                    sequenced: true,
                    wildType: false,
                    variantAllele: 'A',
                    refseqMrnaId:
                        'NM_001126112.2,NM_001276761.1,NM_001276760.1,NM_000546.5,NM_0011',
                    proteinPosStart: 248,
                    proteinPosEnd: 248,
                    molecularProfileAlterationType: 'MUTATION_EXTENDED',
                    alterationSubType: 'missense',
                    alterationType: 'MUTATION_EXTENDED',
                },
            ],
            VDAyNjpjaG9sX251c18yMDEy: [
                {
                    uniqueSampleKey: 'VDAyNjpjaG9sX251c18yMDEy',
                    uniquePatientKey: 'VDAyNjpjaG9sX251c18yMDEy',
                    molecularProfileId: 'chol_nus_2012_mutations',
                    sampleId: 'T026',
                    patientId: 'T026',
                    entrezGeneId: 7157,
                    gene: {
                        entrezGeneId: 7157,
                        hugoGeneSymbol: 'TP53',
                        type: 'protein-coding',
                        cytoband: '17p13.1',
                        length: 19149,
                        chromosome: '17',
                    },
                    studyId: 'chol_nus_2012',
                    center: 'NUS',
                    mutationStatus: 'NA',
                    validationStatus: 'NA',
                    tumorAltCount: -1,
                    tumorRefCount: -1,
                    normalAltCount: -1,
                    normalRefCount: -1,
                    startPosition: 7579470,
                    endPosition: 7579471,
                    referenceAllele: '-',
                    proteinChange: 'V73Rfs*76',
                    mutationType: 'Frame_Shift_Ins',
                    functionalImpactScore: 'NA',
                    fisValue: 1.4013e-45,
                    linkXvar: 'NA',
                    linkPdb: 'NA',
                    linkMsa: 'NA',
                    ncbiBuild: 'GRCh37',
                    variantType: 'INS',
                    keyword: 'TP53 truncating',
                    driverFilter: '',
                    driverFilterAnnotation: '',
                    driverTiersFilter: '',
                    driverTiersFilterAnnotation: '',
                    sequenced: true,
                    wildType: false,
                    variantAllele: 'G',
                    refseqMrnaId:
                        'NM_001126112.2,NM_001276761.1,NM_001276760.1,NM_000546.5,NM_0011',
                    proteinPosStart: 72,
                    proteinPosEnd: 73,
                    molecularProfileAlterationType: 'MUTATION_EXTENDED',
                    alterationSubType: 'frameshift',
                    alterationType: 'MUTATION_EXTENDED',
                },
            ],
            VTA0NDpjaG9sX251c18yMDEy: [
                {
                    uniqueSampleKey: 'VTA0NDpjaG9sX251c18yMDEy',
                    uniquePatientKey: 'VTA0NDpjaG9sX251c18yMDEy',
                    molecularProfileId: 'chol_nus_2012_mutations',
                    sampleId: 'U044',
                    patientId: 'U044',
                    entrezGeneId: 7157,
                    gene: {
                        entrezGeneId: 7157,
                        hugoGeneSymbol: 'TP53',
                        type: 'protein-coding',
                        cytoband: '17p13.1',
                        length: 19149,
                        chromosome: '17',
                    },
                    studyId: 'chol_nus_2012',
                    center: 'NUS',
                    mutationStatus: 'NA',
                    validationStatus: 'NA',
                    tumorAltCount: -1,
                    tumorRefCount: -1,
                    normalAltCount: -1,
                    normalRefCount: -1,
                    startPosition: 7579377,
                    endPosition: 7579377,
                    referenceAllele: 'G',
                    proteinChange: 'Q104*',
                    mutationType: 'Nonsense_Mutation',
                    functionalImpactScore: 'NA',
                    fisValue: 0,
                    linkXvar:
                        'getma.org/?cm=var&var=hg19,17,7579377,G,A&fts=all',
                    linkPdb: 'NA',
                    linkMsa: 'NA',
                    ncbiBuild: 'GRCh37',
                    variantType: 'SNP',
                    keyword: 'TP53 truncating',
                    driverFilter: '',
                    driverFilterAnnotation: '',
                    driverTiersFilter: '',
                    driverTiersFilterAnnotation: '',
                    sequenced: true,
                    wildType: false,
                    variantAllele: 'A',
                    refseqMrnaId:
                        'NM_001126112.2,NM_001276761.1,NM_001276760.1,NM_000546.5,NM_0011',
                    proteinPosStart: 104,
                    proteinPosEnd: 104,
                    molecularProfileAlterationType: 'MUTATION_EXTENDED',
                    alterationSubType: 'nonsense',
                    alterationType: 'MUTATION_EXTENDED',
                },
            ],
            VzA0MDpjaG9sX251c18yMDEy: [
                {
                    uniqueSampleKey: 'VzA0MDpjaG9sX251c18yMDEy',
                    uniquePatientKey: 'VzA0MDpjaG9sX251c18yMDEy',
                    molecularProfileId: 'chol_nus_2012_mutations',
                    sampleId: 'W040',
                    patientId: 'W040',
                    entrezGeneId: 7157,
                    gene: {
                        entrezGeneId: 7157,
                        hugoGeneSymbol: 'TP53',
                        type: 'protein-coding',
                        cytoband: '17p13.1',
                        length: 19149,
                        chromosome: '17',
                    },
                    studyId: 'chol_nus_2012',
                    center: 'NUS',
                    mutationStatus: 'NA',
                    validationStatus: 'NA',
                    tumorAltCount: -1,
                    tumorRefCount: -1,
                    normalAltCount: -1,
                    normalRefCount: -1,
                    startPosition: 7577564,
                    endPosition: 7577565,
                    referenceAllele: '-',
                    proteinChange: 'N239Kfs*25',
                    mutationType: 'Frame_Shift_Ins',
                    functionalImpactScore: 'NA',
                    fisValue: 1.4013e-45,
                    linkXvar: 'NA',
                    linkPdb: 'NA',
                    linkMsa: 'NA',
                    ncbiBuild: 'GRCh37',
                    variantType: 'INS',
                    keyword: 'TP53 truncating',
                    driverFilter: '',
                    driverFilterAnnotation: '',
                    driverTiersFilter: '',
                    driverTiersFilterAnnotation: '',
                    sequenced: true,
                    wildType: false,
                    variantAllele: 'T',
                    refseqMrnaId: 'NM_001126112.2',
                    proteinPosStart: 239,
                    proteinPosEnd: 239,
                    molecularProfileAlterationType: 'MUTATION_EXTENDED',
                    alterationSubType: 'frameshift',
                    alterationType: 'MUTATION_EXTENDED',
                },
            ],
        },
    },
    studies: [
        {
            name:
                'Cholangiocarcinoma (National University of Singapore, Nat Genet 2012)',
            description:
                'Exome Sequencing for Opisthorchis viverrini-related cholangiocarcinoma in 8 O.viverrini-related tumors and matched normal tissue.',
            publicStudy: true,
            pmid: '22561520',
            citation: 'Ong et al. Nat Genet 2012',
            groups: 'PUBLIC',
            status: 0,
            importDate: '2017-11-10 05:00:00',
            allSampleCount: 8,
            sequencedSampleCount: 8,
            cnaSampleCount: 0,
            mrnaRnaSeqSampleCount: 0,
            mrnaRnaSeqV2SampleCount: 0,
            mrnaMicroarraySampleCount: 0,
            miRnaSampleCount: 0,
            methylationHm27SampleCount: 0,
            rppaSampleCount: 0,
            completeSampleCount: 0,
            studyId: 'chol_nus_2012',
            cancerTypeId: 'chol',
            cancerType: {
                name: 'Cholangiocarcinoma',
                clinicalTrialKeywords: 'cholangiocarcinoma',
                dedicatedColor: 'Green',
                shortName: 'CHOL',
                parent: 'biliary_tract',
                cancerTypeId: 'chol',
            },
        },
        {
            name:
                'Pancreatic Neuroendocrine Tumors (Johns Hopkins University, Science 2011)',
            description:
                'Whole exome sequencing of 10 pancreatic neuroendocrine tumor patients. <A HREF="https://www.sciencemag.org/content/331/6021/1199/suppl/DC1">',
            publicStudy: true,
            pmid: '21252315',
            citation: 'Jiao et al. Science 2011',
            groups: 'PUBLIC',
            status: 0,
            importDate: '2017-11-15 05:00:00',
            allSampleCount: 10,
            sequencedSampleCount: 10,
            cnaSampleCount: 0,
            mrnaRnaSeqSampleCount: 0,
            mrnaRnaSeqV2SampleCount: 0,
            mrnaMicroarraySampleCount: 0,
            miRnaSampleCount: 0,
            methylationHm27SampleCount: 0,
            rppaSampleCount: 0,
            completeSampleCount: 0,
            studyId: 'panet_jhu_2011',
            cancerTypeId: 'panet',
            cancerType: {
                name: 'Pancreatic Neuroendocrine Tumor',
                clinicalTrialKeywords: 'pancreatic neuroendocrine tumor',
                dedicatedColor: 'Purple',
                shortName: 'PANET',
                parent: 'pancreas',
                cancerTypeId: 'panet',
            },
        },
    ],
    studyMap: {
        chol_nus_2012: {
            name:
                'Cholangiocarcinoma (National University of Singapore, Nat Genet 2012)',
            description:
                'Exome Sequencing for Opisthorchis viverrini-related cholangiocarcinoma in 8 O.viverrini-related tumors and matched normal tissue.',
            publicStudy: true,
            pmid: '22561520',
            citation: 'Ong et al. Nat Genet 2012',
            groups: 'PUBLIC',
            status: 0,
            importDate: '2017-11-10 05:00:00',
            allSampleCount: 8,
            sequencedSampleCount: 8,
            cnaSampleCount: 0,
            mrnaRnaSeqSampleCount: 0,
            mrnaRnaSeqV2SampleCount: 0,
            mrnaMicroarraySampleCount: 0,
            miRnaSampleCount: 0,
            methylationHm27SampleCount: 0,
            rppaSampleCount: 0,
            completeSampleCount: 0,
            studyId: 'chol_nus_2012',
            cancerTypeId: 'chol',
            cancerType: {
                name: 'Cholangiocarcinoma',
                clinicalTrialKeywords: 'cholangiocarcinoma',
                dedicatedColor: 'Green',
                shortName: 'CHOL',
                parent: 'biliary_tract',
                cancerTypeId: 'chol',
            },
        },
        panet_jhu_2011: {
            name:
                'Pancreatic Neuroendocrine Tumors (Johns Hopkins University, Science 2011)',
            description:
                'Whole exome sequencing of 10 pancreatic neuroendocrine tumor patients. <A HREF="https://www.sciencemag.org/content/331/6021/1199/suppl/DC1">',
            publicStudy: true,
            pmid: '21252315',
            citation: 'Jiao et al. Science 2011',
            groups: 'PUBLIC',
            status: 0,
            importDate: '2017-11-15 05:00:00',
            allSampleCount: 10,
            sequencedSampleCount: 10,
            cnaSampleCount: 0,
            mrnaRnaSeqSampleCount: 0,
            mrnaRnaSeqV2SampleCount: 0,
            mrnaMicroarraySampleCount: 0,
            miRnaSampleCount: 0,
            methylationHm27SampleCount: 0,
            rppaSampleCount: 0,
            completeSampleCount: 0,
            studyId: 'panet_jhu_2011',
            cancerTypeId: 'panet',
            cancerType: {
                name: 'Pancreatic Neuroendocrine Tumor',
                clinicalTrialKeywords: 'pancreatic neuroendocrine tumor',
                dedicatedColor: 'Purple',
                shortName: 'PANET',
                parent: 'pancreas',
                cancerTypeId: 'panet',
            },
        },
    },
};
