declare const styles: {
  readonly "absolutePanel": string;
  readonly "actionButtons": string;
  readonly "autosubmitToggle": string;
  readonly "bookmarkButton": string;
  readonly "content": string;
  readonly "description": string;
  readonly "editableSpanStyles": string;
  readonly "filterClinicalAttrName": string;
  readonly "hesitateControls": string;
  readonly "hesitateControlsAlign": string;
  readonly "mainTabs": string;
  readonly "parentGroupLogic": string;
  readonly "selectedInfo": string;
  readonly "selectedInfoCheckbox": string;
  readonly "selectedInfoLoadingIndicator": string;
  readonly "studyFilterResult": string;
  readonly "studyViewAutoMargin": string;
  readonly "studyViewLoadingIndicator": string;
  readonly "studyViewPageGearMenu": string;
  readonly "studyViewSurvivalPlot": string;
  readonly "studyViewSurvivalPlotBody": string;
  readonly "studyViewSurvivalPlotTitle": string;
  readonly "summary": string;
  readonly "summaryClearAllBtn": string;
  readonly "titleMeta": string;
  readonly "tooltip": string;
  readonly "userSelections": string;
};
export = styles;

