declare const styles: {
  readonly "CancerType": string;
  readonly "DeletedStudy": string;
  readonly "Level0": string;
  readonly "Level1": string;
  readonly "Level2": string;
  readonly "Level3": string;
  readonly "Level4": string;
  readonly "SelectAll": string;
  readonly "SelectedStudyList": string;
  readonly "Study": string;
  readonly "StudyLinks": string;
  readonly "StudyList": string;
  readonly "StudyMeta": string;
  readonly "StudyName": string;
  readonly "StudySamples": string;
  readonly "UnauthorizedStudy": string;
  readonly "deselectAll": string;
  readonly "fadein": string;
  readonly "icon": string;
  readonly "iconWithTooltip": string;
  readonly "indentArrow": string;
  readonly "infoCircleIcon": string;
  readonly "lockIcon": string;
  readonly "selectAllStudies": string;
  readonly "summaryIcon": string;
  readonly "tooltip": string;
  readonly "trashIcon": string;
};
export = styles;

